### ISSUE TITLE
Add-on does not work on Anki 23.12.1

### ISSUE THREAD

**Issue by Exponent4806** [abdnh/anki-zim-reader#20]
The add-on cannot be used on the latest version of Anki!

Would it be possible to find a solution ?  I helped to fund the add-on adding German support via a freelancer platform but now this critical errors makes it impossible to use !  :( 

Best regards from Germany....

------------------
Anki 23.12.1 (1a1d4d54) (src) (ao)
Python 3.11.6 Qt 6.6.1 PyQt 6.6.1
Platform: Linux-6.6.10-arch1-1-x86_64-with-glibc2.38

When loading ZIM Reader - Look up words in Wiktionary:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/aqt/addons.py", line 245, in loadAddons
    __import__(addon.dir_name)
  File "/home/m/.local/share/Anki2/addons21/951350249/__init__.py", line 4, in <module>
    from . import main
  File "/home/m/.local/share/Anki2/addons21/951350249/main.py", line 23, in <module>
    from . import popup
  File "/home/m/.local/share/Anki2/addons21/951350249/popup.py", line 14, in <module>
    from . import server
  File "/home/m/.local/share/Anki2/addons21/951350249/server.py", line 13, in <module>
    from .dictionaries import DefaultParser, Parser, ZIMDict
  File "/home/m/.local/share/Anki2/addons21/951350249/dictionaries/__init__.py", line 7, in <module>
    from .dictionary import DictEntry, ZIMDict
  File "/home/m/.local/share/Anki2/addons21/951350249/dictionaries/dictionary.py", line 13, in <module>
    from ..client import ZIMItem, init_client
  File "/home/m/.local/share/Anki2/addons21/951350249/client.py", line 142, in <module>
    assert _client_class
AssertionError

**Comment by abdnh** [comment]
Thank you for your support! I'll look into the error today!

**Comment by abdnh** [comment]
I assume you're not using the official Anki package? The add-on will need updating each time Anki's Python version is changed. The official package is at 3.9 but you're using Python 3.11. I'll try to build a version that works with Python 3.11 and send it here (I probably won't upload that to AnkiWeb yet because it'll increase the size unnecessarily for most users)

**Comment by abdnh** [comment]
Does this work for you?
[zim_reader_ankiweb.zip](https://github.com/abdnh/anki-zim-reader/files/13941336/zim_reader_ankiweb.zip)

**Comment by Exponent4806** [comment]
> Does this work for you? [zim_reader_ankiweb.zip](https://github.com/abdnh/anki-zim-reader/files/13941336/zim_reader_ankiweb.zip)

Yes ! Thanks for your prompt reply and kind offer of help!

I use Anki from the Arch user Repository (Anki-bin). I did not expect that the package from Arch Linux could cause this issue with Anki.

Maybe the simplest solution is to always use the official build...! 

Thanks for your great work....!

**Comment by abdnh** [comment]
This add-on is particularly sensitive to the Python version because it packages libzim.
