### ISSUE TITLE
Loading error (Manjaro Linux - Anki 2.5.4)

### ISSUE THREAD

**Issue by Immunize2** [abdnh/anki-zim-reader#4]
**OS:** Manjaro KDE Stable (latest version)
**Anki Version** ⁨2.1.54 (b6a7760c)⁩
Add-ons: disabled
Python 3.10.6 Qt 6.3.1 PyQt 6.3.1

Thanks for sharing the latest version of the add-on via Fiverr.  After installing the add-on, I get this error after opening Anki:

> -------------------
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨ZIM Reader⁩':
⁨Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aqt/addons.py", line 244, in loadAddons
    __import__(addon.dir_name)
  File "/home/m/.local/share/Anki2/addons21/zim_reader/__init__.py", line 4, in <module>
    from . import main
  File "/home/m/.local/share/Anki2/addons21/zim_reader/main.py", line 18, in <module>
    from . import popup
  File "/home/m/.local/share/Anki2/addons21/zim_reader/popup.py", line 14, in <module>
    from . import server
  File "/home/m/.local/share/Anki2/addons21/zim_reader/server.py", line 11, in <module>
    from .dictionaries import DefaultParser, Parser, ZIMDict
  File "/home/m/.local/share/Anki2/addons21/zim_reader/dictionaries/__init__.py", line 7, in <module>
    from .dictionary import DictEntry, ZIMDict
  File "/home/m/.local/share/Anki2/addons21/zim_reader/dictionaries/dictionary.py", line 11, in <module>
    from zimply_core.zim_core import Article, ZIMClient
  File "/home/m/.local/share/Anki2/addons21/zim_reader/vendor/zimply_core/zim_core.py", line 56, in <module>
    import zstandard
  File "/home/m/.local/share/Anki2/addons21/zim_reader/vendor/zstandard/__init__.py", line 39, in <module>
    from .backend_c import *  # type: ignore
ModuleNotFoundError: No module named 'zstandard.backend_c'

------------------

I cannot use the add-on. It does not appear via GUI.

Please let me know if I could provide you with more info. Thank you very much !

**Comment by abdnh** [comment]
Ah, it seems a library used by the add-on depends on platform-specific files, so the add-on needs to be build separately for each platform or at least all platform-specific files needs to bundled together (The version I sent you is built on Windows and is missing the required Linux files).

For now, try this build instead:
[zim_reader-linux.zip](https://github.com/abdnh/anki-zim-reader/files/9691495/zim_reader-linux.zip)

**Comment by Immunize2** [comment]
Thanks for sharing the compiled version ! It can be installed without errors.

Unfortunately, the add-on cannot fetch any data from the German Wiktionary. I am not sure if the problem is platform-specific or not. 

There are only 3 options in the "PARSER":
- Default
- Greek
- Spanish

**German parser is not among the options via GUI.** 

When I try to "fetch" data from the Wiktionary  I get this error:

I tried several german words exactly as they are written in the German Wiktionary and all failed ! No data gets "fetched" at all. 

I suspect that the issue is that there is no "German.py" file in the add-on files. Alternatively, if the code to parse the German wiktionary is written in another .py file it is not working :(

**Comment by abdnh** [comment]
> German parser is not among the options via GUI.

Sorry. I mistakenly built the package from the version on GitHub, which doesn't include the German version yet. Building the add-on for multiple platforms is a pain and I'm busy figuring it out. Will send you a new version later.

**Comment by abdnh** [comment]
[zim_reader-multi.zip](https://github.com/abdnh/anki-zim-reader/files/9692353/zim_reader-multi.zip)


Let me know how this goes.

**Comment by Immunize2** [comment]
_I get an error after loading the add-on. The same as the first time._

---------------------
⁨Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aqt/addons.py", line 244, in loadAddons
    __import__(addon.dir_name)
  File "/home/m/.local/share/Anki2/addons21/zim_reader/__init__.py", line 4, in <module>
    from . import main
  File "/home/m/.local/share/Anki2/addons21/zim_reader/main.py", line 22, in <module>
    from . import popup
  File "/home/m/.local/share/Anki2/addons21/zim_reader/popup.py", line 14, in <module>
    from . import server
  File "/home/m/.local/share/Anki2/addons21/zim_reader/server.py", line 11, in <module>
    from .dictionaries import DefaultParser, Parser, ZIMDict
  File "/home/m/.local/share/Anki2/addons21/zim_reader/dictionaries/__init__.py", line 7, in <module>
    from .dictionary import DictEntry, ZIMDict
  File "/home/m/.local/share/Anki2/addons21/zim_reader/dictionaries/dictionary.py", line 11, in <module>
    from zimply_core.zim_core import Article, ZIMClient
  File "/home/m/.local/share/Anki2/addons21/zim_reader/vendor/zimply_core/zim_core.py", line 56, in <module>
    import zstandard
  File "/home/m/.local/share/Anki2/addons21/zim_reader/vendor/zstandard/__init__.py", line 39, in <module>
    from .backend_c import *  # type: ignore
ModuleNotFoundError: No module named 'zstandard.backend_c'
-------------------

**Comment by abdnh** [comment]
OK. This build works on my Ubuntu but I expected it won't work on other distros or different versions of the same distro.
I'm investigating an alternative to the python-zstandard library that will hopefully work more consistently across all platforms. Will post an update soon.

**Comment by abdnh** [comment]
Does this work on your distro?

[zim_reader-pyzstd-multi.zip](https://github.com/abdnh/anki-zim-reader/files/9692942/zim_reader-pyzstd-multi.zip)

**Comment by Immunize2** [comment]
> Does this work on your distro?

Yes ! It works perfectly on Manjaro KDE !  

I queried 5 words and it works fine with all the parameters.
